// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

<<<<<<< HEAD
#define BOOKERLY_12_FONT_ID (1888579308)
#define BOOKERLY_14_FONT_ID (438244413)
#define BOOKERLY_16_FONT_ID (1839167134)
#define BOOKERLY_18_FONT_ID (-679450484)
#define NOTOSANS_12_FONT_ID (1837309591)
#define NOTOSANS_14_FONT_ID (1560039867)
#define NOTOSANS_16_FONT_ID (-746851375)
#define NOTOSANS_18_FONT_ID (-2027619823)
#define UI_10_FONT_ID (-1476394976)
#define UI_12_FONT_ID (-920168645)
#define SMALL_FONT_ID (674098198)

